name = "urlshortener"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]
routes = [{ pattern = "shortener.web.id", custom_domain = true }]

[[d1_databases]]
binding = "DB"
database_name = "EdgeLinkDB"
database_id = "31553975-7285-4e74-9a6d-1b14f16fb113"
migrations_dir = "drizzle/migrations"

[observability]
enabled = true


[assets]
directory = "src/frontend"
